
path: C:/Users/bavyk/PycharmProjects/detector_digits_yolo8/data
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 11
names: ['.', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
